spring.application.name=multiboxd

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
tmdb.api.key=${TMDB_API_KEY}

tmdb.base.url=https://api.themoviedb.org/3